version: '3.4'

### Services ################################################################################################'
services:
  #----- Bug.Api -----------------------------------------------------------------------------------------'        
  bug.api:
    image: ${DOCKER_REGISTRY-}bugapi
    build:
      context: .
      dockerfile: Bug.Api/Dockerfile
    environment:    
      - FhirServerConfig__ServiceBaseUrl=https://localhost:8443
      - FhirServerConfig__DefaultFhirFormat=json
      - FhirServerConfig__ServerDefaultTimeZoneTimeSpan=10:00:00
      - FhirServerConfig__CahceSlidingExpirationMinites=10
      - FhirServerConfig__EnforceRelativeResourceReferentialIntegrity=True
    ports:
        - "8080:80"
        - "8443:443"
    networks:
        - bugNet
  #----- postgres SQL DB -----------------------------------------------------------------------------------------'        
  postgres:
    container_name: postgresSQL
    image: postgres
    environment:
      POSTGRES_USER: angusbmillar
      POSTGRES_PASSWORD: 3agepufa
      POSTGRES_DB: BugDb
      PGDATA: /data/postgres
    volumes:
        - postgres:/data/postgres
    #Don't need to expose post as the network 'postgres' allows the containes to talk to each other'
    ports:
      - "5432:5432"
    networks:
        - bugNet
    restart: unless-stopped
  
  #----- PgAdmin -----------------------------------------------------------------------------------------------'        
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: angusbmillar@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 3agepufa
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
        - "5050:80"
    networks:
        - bugNet
    restart: unless-stopped

    #----- PgAdmin -----------------------------------------------------------------------------------------------'        
  redis:
    container_name: Redis
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - bugNet
    volumes:
     - redisdata:/data



### Networks ################################################################################################'

networks:
  bugNet:
    driver: bridge

### Volumes ################################################################################################'
volumes:
  postgres:
  pgadmin:
  redisdata:
