CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "FhirVersion" (
    id integer NOT NULL,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    code character varying(128) NOT NULL,
    CONSTRAINT "PK_FhirVersion" PRIMARY KEY (id)
);

CREATE TABLE "HttpStatusCode" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    number integer NOT NULL,
    code character varying(128) NOT NULL,
    CONSTRAINT "PK_HttpStatusCode" PRIMARY KEY (id)
);

CREATE TABLE "Method" (
    id integer NOT NULL,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    code character varying(128) NOT NULL,
    CONSTRAINT "PK_Method" PRIMARY KEY (id)
);

CREATE TABLE "ResourceType" (
    id integer NOT NULL,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    code character varying(50) NOT NULL,
    CONSTRAINT "PK_ResourceType" PRIMARY KEY (id)
);

CREATE TABLE "SearchParamType" (
    id integer NOT NULL,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    code character varying(128) NOT NULL,
    CONSTRAINT "PK_SearchParamType" PRIMARY KEY (id)
);

CREATE TABLE "ResourceStore" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    resource_id character varying(128) NOT NULL,
    version_id integer NOT NULL,
    is_deleted boolean NOT NULL,
    is_current boolean NOT NULL,
    last_updated timestamp without time zone NOT NULL,
    resource_blob bytea NULL,
    fk_resourcetype_id integer NOT NULL,
    fk_fhirversion_id integer NOT NULL,
    fk_method_id integer NOT NULL,
    fk_httpstatuscode_id integer NOT NULL,
    CONSTRAINT "PK_ResourceStore" PRIMARY KEY (id),
    CONSTRAINT "FK_ResourceStore_FhirVersion_fk_fhirversion_id" FOREIGN KEY (fk_fhirversion_id) REFERENCES "FhirVersion" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_ResourceStore_HttpStatusCode_fk_httpstatuscode_id" FOREIGN KEY (fk_httpstatuscode_id) REFERENCES "HttpStatusCode" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_ResourceStore_Method_fk_method_id" FOREIGN KEY (fk_method_id) REFERENCES "Method" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_ResourceStore_ResourceType_fk_resourcetype_id" FOREIGN KEY (fk_resourcetype_id) REFERENCES "ResourceType" (id) ON DELETE CASCADE
);

CREATE TABLE "SearchParameter" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    name character varying(128) NOT NULL,
    description text NULL,
    fk_searchparamtype_id integer NOT NULL,
    url character varying(450) NULL,
    fhir_path text NULL,
    fk_fhirversion_id integer NOT NULL,
    CONSTRAINT "PK_SearchParameter" PRIMARY KEY (id),
    CONSTRAINT "FK_SearchParameter_FhirVersion_fk_fhirversion_id" FOREIGN KEY (fk_fhirversion_id) REFERENCES "FhirVersion" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_SearchParameter_SearchParamType_fk_searchparamtype_id" FOREIGN KEY (fk_searchparamtype_id) REFERENCES "SearchParamType" (id) ON DELETE CASCADE
);

CREATE TABLE "SearchParameterComponent" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    "FkSearchParameterId" integer NOT NULL,
    definition character varying(450) NOT NULL,
    expression text NOT NULL,
    CONSTRAINT "PK_SearchParameterComponent" PRIMARY KEY (id),
    CONSTRAINT "FK_SearchParameterComponent_SearchParameter_FkSearchParameterId" FOREIGN KEY ("FkSearchParameterId") REFERENCES "SearchParameter" (id) ON DELETE CASCADE
);

CREATE TABLE "SearchParameterResourceType" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    "FkSearchParameterId" integer NOT NULL,
    fk_resourcetype_id integer NOT NULL,
    CONSTRAINT "PK_SearchParameterResourceType" PRIMARY KEY (id),
    CONSTRAINT "FK_SearchParameterResourceType_ResourceType_fk_resourcetype_id" FOREIGN KEY (fk_resourcetype_id) REFERENCES "ResourceType" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_SearchParameterResourceType_SearchParameter_FkSearchParamet~" FOREIGN KEY ("FkSearchParameterId") REFERENCES "SearchParameter" (id) ON DELETE CASCADE
);

CREATE TABLE "SearchParameterTargetResourceType" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    "FkSearchParameterId" integer NOT NULL,
    fk_resourcetype_id integer NOT NULL,
    CONSTRAINT "PK_SearchParameterTargetResourceType" PRIMARY KEY (id),
    CONSTRAINT "FK_SearchParameterTargetResourceType_ResourceType_fk_resourcet~" FOREIGN KEY (fk_resourcetype_id) REFERENCES "ResourceType" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_SearchParameterTargetResourceType_SearchParameter_FkSearchP~" FOREIGN KEY ("FkSearchParameterId") REFERENCES "SearchParameter" (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "Unique_Number" ON "HttpStatusCode" (number);

CREATE INDEX "IX_ResourceStore_fk_httpstatuscode_id" ON "ResourceStore" (fk_httpstatuscode_id);

CREATE INDEX "IX_ResourceStore_fk_method_id" ON "ResourceStore" (fk_method_id);

CREATE INDEX "IX_ResourceStore_fk_resourcetype_id" ON "ResourceStore" (fk_resourcetype_id);

CREATE INDEX "Ix_LastUpdated" ON "ResourceStore" (last_updated);

CREATE UNIQUE INDEX "UniqueIx_FhirVer_ResType_ResId_ResVer" ON "ResourceStore" (fk_fhirversion_id, fk_resourcetype_id, resource_id, version_id);

CREATE INDEX "IX_SearchParameter_fk_fhirversion_id" ON "SearchParameter" (fk_fhirversion_id);

CREATE INDEX "IX_SearchParameter_fk_searchparamtype_id" ON "SearchParameter" (fk_searchparamtype_id);

CREATE INDEX "IX_SearchParameterComponent_FkSearchParameterId" ON "SearchParameterComponent" ("FkSearchParameterId");

CREATE INDEX "IX_SearchParameterResourceType_fk_resourcetype_id" ON "SearchParameterResourceType" (fk_resourcetype_id);

CREATE INDEX "IX_SearchParameterResourceType_FkSearchParameterId" ON "SearchParameterResourceType" ("FkSearchParameterId");

CREATE INDEX "IX_SearchParameterTargetResourceType_fk_resourcetype_id" ON "SearchParameterTargetResourceType" (fk_resourcetype_id);

CREATE INDEX "IX_SearchParameterTargetResourceType_FkSearchParameterId" ON "SearchParameterTargetResourceType" ("FkSearchParameterId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200316080756_First', '3.1.1');

