

using Bug.Logic.DomainModel;
using System;
using System.Collections.Generic;
using System.Text;

//This class was auto code generated by a T4 Template found here: Bug.CodeGeneration.T4Templates.SearchParameterTargetResourceName: SearchParameterTargetResourceNameSeed.tt
//
// Last Generated : 13/03/2020 12:07:45 PM
//
namespace Bug.Data.Seeding
{
  public static class SearchParameterComponentSeed
  {
    public static SearchParameterComponent[] GetSeedData(DateTime dateTimeNow)
    {
      var List = new List<SearchParameterComponent>()
      {
        new SearchParameterComponent()
        {
            Id = 1,
            FkSearchParameterId = 439,
            Definition = "http://hl7.org/fhir/SearchParameter/DocumentReference-relatesto", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 2,
            FkSearchParameterId = 439,
            Definition = "http://hl7.org/fhir/SearchParameter/DocumentReference-relation", 
            Expression = "target", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 3,
            FkSearchParameterId = 539,
            Definition = "http://hl7.org/fhir/SearchParameter/Group-characteristic", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 4,
            FkSearchParameterId = 539,
            Definition = "http://hl7.org/fhir/SearchParameter/Group-value", 
            Expression = "value", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 5,
            FkSearchParameterId = 787,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 6,
            FkSearchParameterId = 787,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-value-concept", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 7,
            FkSearchParameterId = 788,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 8,
            FkSearchParameterId = 788,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-value-date", 
            Expression = "value.as(DateTime) | value.as(Period)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 9,
            FkSearchParameterId = 789,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 10,
            FkSearchParameterId = 789,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-value-quantity", 
            Expression = "value.as(Quantity)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 11,
            FkSearchParameterId = 790,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 12,
            FkSearchParameterId = 790,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-value-string", 
            Expression = "value.as(string)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 13,
            FkSearchParameterId = 792,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-combo-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 14,
            FkSearchParameterId = 792,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-combo-value-concept", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 15,
            FkSearchParameterId = 793,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-combo-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 16,
            FkSearchParameterId = 793,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-combo-value-quantity", 
            Expression = "value.as(Quantity)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 17,
            FkSearchParameterId = 798,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-component-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 18,
            FkSearchParameterId = 798,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-component-value-concept", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 19,
            FkSearchParameterId = 799,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-component-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 20,
            FkSearchParameterId = 799,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-component-value-quantity", 
            Expression = "value.as(Quantity)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 21,
            FkSearchParameterId = 808,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-related-target", 
            Expression = "target", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 22,
            FkSearchParameterId = 808,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-related-type", 
            Expression = "type", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 23,
            FkSearchParameterId = 1071,
            Definition = "http://hl7.org/fhir/SearchParameter/Sequence-chromosome", 
            Expression = "%resource.referenceSeq.chromosome", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 24,
            FkSearchParameterId = 1071,
            Definition = "http://hl7.org/fhir/SearchParameter/Sequence-start", 
            Expression = "start", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 25,
            FkSearchParameterId = 1071,
            Definition = "http://hl7.org/fhir/SearchParameter/Sequence-end", 
            Expression = "end", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 26,
            FkSearchParameterId = 1255,
            Definition = "http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 27,
            FkSearchParameterId = 1255,
            Definition = "http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 28,
            FkSearchParameterId = 1256,
            Definition = "http://hl7.org/fhir/SearchParameter/ActivityDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 29,
            FkSearchParameterId = 1256,
            Definition = "http://hl7.org/fhir/SearchParameter/ActivityDefinition-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 30,
            FkSearchParameterId = 1363,
            Definition = "http://hl7.org/fhir/SearchParameter/conformance-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 31,
            FkSearchParameterId = 1363,
            Definition = "http://hl7.org/fhir/SearchParameter/conformance-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 32,
            FkSearchParameterId = 1364,
            Definition = "http://hl7.org/fhir/SearchParameter/conformance-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 33,
            FkSearchParameterId = 1364,
            Definition = "http://hl7.org/fhir/SearchParameter/conformance-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 34,
            FkSearchParameterId = 1417,
            Definition = "http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 35,
            FkSearchParameterId = 1417,
            Definition = "http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 36,
            FkSearchParameterId = 1418,
            Definition = "http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 37,
            FkSearchParameterId = 1418,
            Definition = "http://hl7.org/fhir/SearchParameter/ChargeItemDefinition-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 38,
            FkSearchParameterId = 1671,
            Definition = "http://hl7.org/fhir/SearchParameter/DocumentReference-relatesto", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 39,
            FkSearchParameterId = 1671,
            Definition = "http://hl7.org/fhir/SearchParameter/DocumentReference-relation", 
            Expression = "target", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 40,
            FkSearchParameterId = 1686,
            Definition = "http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 41,
            FkSearchParameterId = 1686,
            Definition = "http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 42,
            FkSearchParameterId = 1687,
            Definition = "http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 43,
            FkSearchParameterId = 1687,
            Definition = "http://hl7.org/fhir/SearchParameter/EffectEvidenceSynthesis-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 44,
            FkSearchParameterId = 1745,
            Definition = "http://hl7.org/fhir/SearchParameter/EventDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 45,
            FkSearchParameterId = 1745,
            Definition = "http://hl7.org/fhir/SearchParameter/EventDefinition-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 46,
            FkSearchParameterId = 1746,
            Definition = "http://hl7.org/fhir/SearchParameter/EventDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 47,
            FkSearchParameterId = 1746,
            Definition = "http://hl7.org/fhir/SearchParameter/EventDefinition-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 48,
            FkSearchParameterId = 1767,
            Definition = "http://hl7.org/fhir/SearchParameter/Evidence-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 49,
            FkSearchParameterId = 1767,
            Definition = "http://hl7.org/fhir/SearchParameter/Evidence-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 50,
            FkSearchParameterId = 1768,
            Definition = "http://hl7.org/fhir/SearchParameter/Evidence-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 51,
            FkSearchParameterId = 1768,
            Definition = "http://hl7.org/fhir/SearchParameter/Evidence-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 52,
            FkSearchParameterId = 1789,
            Definition = "http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 53,
            FkSearchParameterId = 1789,
            Definition = "http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 54,
            FkSearchParameterId = 1790,
            Definition = "http://hl7.org/fhir/SearchParameter/EvidenceVariable-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 55,
            FkSearchParameterId = 1790,
            Definition = "http://hl7.org/fhir/SearchParameter/EvidenceVariable-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 56,
            FkSearchParameterId = 1802,
            Definition = "http://hl7.org/fhir/SearchParameter/ExampleScenario-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 57,
            FkSearchParameterId = 1802,
            Definition = "http://hl7.org/fhir/SearchParameter/ExampleScenario-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 58,
            FkSearchParameterId = 1803,
            Definition = "http://hl7.org/fhir/SearchParameter/ExampleScenario-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 59,
            FkSearchParameterId = 1803,
            Definition = "http://hl7.org/fhir/SearchParameter/ExampleScenario-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 60,
            FkSearchParameterId = 1845,
            Definition = "http://hl7.org/fhir/SearchParameter/Group-characteristic", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 61,
            FkSearchParameterId = 1845,
            Definition = "http://hl7.org/fhir/SearchParameter/Group-value", 
            Expression = "value", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 62,
            FkSearchParameterId = 1958,
            Definition = "http://hl7.org/fhir/SearchParameter/Library-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 63,
            FkSearchParameterId = 1958,
            Definition = "http://hl7.org/fhir/SearchParameter/Library-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 64,
            FkSearchParameterId = 1959,
            Definition = "http://hl7.org/fhir/SearchParameter/Library-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 65,
            FkSearchParameterId = 1959,
            Definition = "http://hl7.org/fhir/SearchParameter/Library-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 66,
            FkSearchParameterId = 2005,
            Definition = "http://hl7.org/fhir/SearchParameter/Measure-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 67,
            FkSearchParameterId = 2005,
            Definition = "http://hl7.org/fhir/SearchParameter/Measure-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 68,
            FkSearchParameterId = 2006,
            Definition = "http://hl7.org/fhir/SearchParameter/Measure-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 69,
            FkSearchParameterId = 2006,
            Definition = "http://hl7.org/fhir/SearchParameter/Measure-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 70,
            FkSearchParameterId = 2131,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-chromosome", 
            Expression = "%resource.referenceSeq.chromosome", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 71,
            FkSearchParameterId = 2131,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-start", 
            Expression = "start", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 72,
            FkSearchParameterId = 2131,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-end", 
            Expression = "end", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 73,
            FkSearchParameterId = 2132,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-chromosome", 
            Expression = "chromosome", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 74,
            FkSearchParameterId = 2132,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-window-start", 
            Expression = "windowStart", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 75,
            FkSearchParameterId = 2132,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-window-end", 
            Expression = "windowEnd", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 76,
            FkSearchParameterId = 2133,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-referenceseqid", 
            Expression = "%resource.referenceSeq.referenceSeqId", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 77,
            FkSearchParameterId = 2133,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-start", 
            Expression = "start", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 78,
            FkSearchParameterId = 2133,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-variant-end", 
            Expression = "end", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 79,
            FkSearchParameterId = 2134,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-referenceseqid", 
            Expression = "referenceSeqId", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 80,
            FkSearchParameterId = 2134,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-window-start", 
            Expression = "windowStart", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 81,
            FkSearchParameterId = 2134,
            Definition = "http://hl7.org/fhir/SearchParameter/MolecularSequence-window-end", 
            Expression = "windowEnd", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 82,
            FkSearchParameterId = 2177,
            Definition = "http://hl7.org/fhir/SearchParameter/clinical-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 83,
            FkSearchParameterId = 2177,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-value-concept", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 84,
            FkSearchParameterId = 2178,
            Definition = "http://hl7.org/fhir/SearchParameter/clinical-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 85,
            FkSearchParameterId = 2178,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-value-date", 
            Expression = "value.as(DateTime) | value.as(Period)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 86,
            FkSearchParameterId = 2179,
            Definition = "http://hl7.org/fhir/SearchParameter/clinical-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 87,
            FkSearchParameterId = 2179,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-value-quantity", 
            Expression = "value.as(Quantity)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 88,
            FkSearchParameterId = 2180,
            Definition = "http://hl7.org/fhir/SearchParameter/clinical-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 89,
            FkSearchParameterId = 2180,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-value-string", 
            Expression = "value.as(string)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 90,
            FkSearchParameterId = 2181,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-combo-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 91,
            FkSearchParameterId = 2181,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-combo-value-concept", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 92,
            FkSearchParameterId = 2182,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-combo-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 93,
            FkSearchParameterId = 2182,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-combo-value-quantity", 
            Expression = "value.as(Quantity)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 94,
            FkSearchParameterId = 2183,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-component-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 95,
            FkSearchParameterId = 2183,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-component-value-concept", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 96,
            FkSearchParameterId = 2184,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-component-code", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 97,
            FkSearchParameterId = 2184,
            Definition = "http://hl7.org/fhir/SearchParameter/Observation-component-value-quantity", 
            Expression = "value.as(Quantity)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 98,
            FkSearchParameterId = 2287,
            Definition = "http://hl7.org/fhir/SearchParameter/PlanDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 99,
            FkSearchParameterId = 2287,
            Definition = "http://hl7.org/fhir/SearchParameter/PlanDefinition-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 100,
            FkSearchParameterId = 2288,
            Definition = "http://hl7.org/fhir/SearchParameter/PlanDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 101,
            FkSearchParameterId = 2288,
            Definition = "http://hl7.org/fhir/SearchParameter/PlanDefinition-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 102,
            FkSearchParameterId = 2341,
            Definition = "http://hl7.org/fhir/SearchParameter/Questionnaire-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 103,
            FkSearchParameterId = 2341,
            Definition = "http://hl7.org/fhir/SearchParameter/Questionnaire-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 104,
            FkSearchParameterId = 2342,
            Definition = "http://hl7.org/fhir/SearchParameter/Questionnaire-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 105,
            FkSearchParameterId = 2342,
            Definition = "http://hl7.org/fhir/SearchParameter/Questionnaire-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 106,
            FkSearchParameterId = 2393,
            Definition = "http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 107,
            FkSearchParameterId = 2393,
            Definition = "http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 108,
            FkSearchParameterId = 2394,
            Definition = "http://hl7.org/fhir/SearchParameter/ResearchDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 109,
            FkSearchParameterId = 2394,
            Definition = "http://hl7.org/fhir/SearchParameter/ResearchDefinition-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 110,
            FkSearchParameterId = 2415,
            Definition = "http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 111,
            FkSearchParameterId = 2415,
            Definition = "http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 112,
            FkSearchParameterId = 2416,
            Definition = "http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 113,
            FkSearchParameterId = 2416,
            Definition = "http://hl7.org/fhir/SearchParameter/ResearchElementDefinition-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 114,
            FkSearchParameterId = 2456,
            Definition = "http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 115,
            FkSearchParameterId = 2456,
            Definition = "http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 116,
            FkSearchParameterId = 2457,
            Definition = "http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 117,
            FkSearchParameterId = 2457,
            Definition = "http://hl7.org/fhir/SearchParameter/RiskEvidenceSynthesis-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 118,
            FkSearchParameterId = 2584,
            Definition = "http://hl7.org/fhir/SearchParameter/TestScript-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 119,
            FkSearchParameterId = 2584,
            Definition = "http://hl7.org/fhir/SearchParameter/TestScript-context-quantity", 
            Expression = "value.as(Quantity) | value.as(Range)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 120,
            FkSearchParameterId = 2585,
            Definition = "http://hl7.org/fhir/SearchParameter/TestScript-context-type", 
            Expression = "code", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        new SearchParameterComponent()
        {
            Id = 121,
            FkSearchParameterId = 2585,
            Definition = "http://hl7.org/fhir/SearchParameter/TestScript-context", 
            Expression = "value.as(CodeableConcept)", 
            Created = dateTimeNow,
            Updated = dateTimeNow
        },
        
      };
      return List.ToArray();
    }
  }
}
